# Generated by Django 5.1 on 2024-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereport',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
