# Generated by Django 5.1 on 2024-09-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articleimage_is_temporary'),
        ('reports', '0002_articlereport_deleted_at_commentreport_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='reported_article',
            field=models.ForeignKey(default=197, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
    ]
