# Generated by Django 5.1 on 2024-09-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='article',
        ),
    ]
