# # version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver --noreload 0.0.0.0:8000"
    environment:
      - DB_HOST=${RDS_HOSTNAME} 
      - DB_NAME=${RDS_DB_NAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network

  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Docker 소켓 접근을 위해 root 사용자로 실행
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 소켓 공유
      - jenkins_home:/var/jenkins_home  
    networks:
      - app_network

volumes:
  jenkins_home:

networks:
  app_network: