# Jenkins 기반 이미지 사용
FROM jenkins/jenkins:lts

# 루트 사용자로 전환
USER root

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common && \
    apt-get update && \
    apt-get install -y docker.io awscli

# Jenkins 사용자로 전환
USER jenkins