# Generated by Django 5.1 on 2024-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunsoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihunsoo',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
