# Generated by Django 5.1 on 2024-09-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hunsoos', '0002_aihunsoo_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihunsoo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aihunsoo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
