# Generated by Django 5.1 on 2024-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(choices=[(0, '연애 훈수'), (1, '집안일 훈수'), (2, '고민 훈수'), (3, '소소 훈수'), (4, '상상 훈수'), (5, '패션 훈수'), (6, '게임 훈수'), (7, '교육 훈수')], unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
