# Generated by Django 5.1 on 2024-08-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(choices=[(0, '연애 훈수'), (1, '집안일 훈수'), (2, '고민 훈수'), (3, '소소 훈수'), (4, '상상 훈수'), (5, '패션 훈수'), (6, '게임 훈수'), (7, '교육 훈수')], primary_key=True, serialize=False, unique=True),
        ),
    ]
