# Generated by Django 5.1 on 2024-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(choices=[(0, '전체'), (1, '일상'), (2, '연애 훈수'), (3, '집안일 훈수'), (4, '고민 훈수'), (5, '소소 훈수'), (6, '상상 훈수'), (7, '패션 훈수'), (8, '게임'), (9, '모바일 게임 훈수'), (10, 'PC 게임 훈수'), (11, '교육 훈수')], primary_key=True, serialize=False, unique=True),
        ),
    ]
