# Generated by Django 5.1 on 2024-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_like_count_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
