# Generated by Django 5.1 on 2024-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_deleted_at_articleimage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
