# Generated by Django 5.1 on 2024-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articleimage_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='is_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
