# Generated by Django 5.1 on 2024-08-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_deleted_at_commentimage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
