# Github Actions CI/CD

name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }} 
      RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
      RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
      RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      RDS_DB_PORT: ${{ secrets.RDS_DB_PORT }}

    steps:
    - uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "RDS_HOSTNAME=${RDS_HOSTNAME}" >> .env
        echo "RDS_DB_NAME=${RDS_DB_NAME}" >> .env
        echo "RDS_USERNAME=${RDS_USERNAME}" >> .env
        echo "RDS_PASSWORD=${RDS_PASSWORD}" >> .env
        echo "RDS_DB_PORT=${RDS_DB_PORT}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose  

    - name: Build and run Docker containers
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run tests
      run: docker-compose run --rm app python manage.py test

    - name: Run tests with coverage
      run: docker-compose run --rm app coverage run manage.py test

    - name: Copy coverage data
      run: docker cp oz_03_collabo-004-be_app_run:/app/.coverage ./.coverage 

    - name: Generate coverage report
      run: coverage report

    - name: Run security checks
      run: docker-compose run --rm app safety check

    - name: Tear down Docker containers
      run: docker-compose down